const ACITIVITY_FEED_CONTAINER = 'activity_feed_container';

const logType = {
  PROFILE_DIFF_APPROVED: 'PROFILE_DIFF_APPROVED',
  PROFILE_DIFF_REJECTED: 'PROFILE_DIFF_REJECTED',
  REQUEST_CREATED: 'REQUEST_CREATED',
  REQUEST_APPROVED: 'REQUEST_APPROVED',
  REQUEST_REJECTED: 'REQUEST_REJECTED',
  REQUEST_BLOCKED: 'REQUEST_BLOCKED',
  REQUEST_CANCELLED: 'REQUEST_CANCELLED',
  TASK: 'task',
  TASK_REQUESTS: 'taskRequests',
  EXTENSION_REQUESTS: 'extensionRequests',
};

const CATEGORY = {
  ALL: 'all',
  OOO: 'ooo',
  TASK: 'task',
  TASK_REQUESTS: 'taskRequests',
  EXTENSION_REQUESTS: 'extensionRequests',
};

const LAST_ELEMENT_CONTAINER = '.virtual';
