const ACITIVITY_FEED_CONTAINER = 'activity_feed_container';

const logType = {
  PROFILE_DIFF_APPROVED: "PROFILE_DIFF_APPROVED",
  PROFILE_DIFF_REJECTED: "PROFILE_DIFF_REJECTED",
  CLOUDFLARE_CACHE_PURGED: "CLOUDFLARE_CACHE_PURGED",
  APPLICATION_UPDATED: "USER_APPLICATION_UPDATED",
  EVENTS_REMOVE_PEER: "EVENTS_REMOVE_PEER",
  APPLICATION_ADDED: "USER_APPLICATION_ADDED",
  TASKS_MISSED_UPDATES_ERRORS: "TASKS_MISSED_UPDATES_ERRORS",
  DISCORD_INVITES: "DISCORD_INVITES",
  EXTERNAL_SERVICE: "EXTERNAL_SERVICE",
  EXTENSION_REQUESTS: "extensionRequests",
  REQUEST_CREATED: "REQUEST_CREATED",
  REQUEST_APPROVED: "REQUEST_APPROVED",
  REQUEST_REJECTED: "REQUEST_REJECTED",
  REQUEST_BLOCKED: "REQUEST_BLOCKED",
  REQUEST_CANCELLED: "REQUEST_CANCELLED",
  TASK:"task"
};

const QUERY_STRING_PARAMS = [logType.EXTENSION_REQUESTS, logType.REQUEST_CREATED,logType.TASK];
