const standupOne = {
  message: 'Progress document retrieved successfully.',
  count: 9,
  data: [
    {
      id: '8hhlqHacZ9iWo3rbWHku',
      date: 1685145600000,
      createdAt: 1685163538297,
      blockers: 'Implement error handling for API endpoints',
      completed: 'Implement error handling for API endpoints',
      planned: 'Implement error handling for API endpoints',
      type: 'user',
      userId: 'YleviOe1SsOML8eitV9W',
    },
    {
      id: 'ANaIkUInoUeAagwMsxHI',
      date: 1685836800000,
      createdAt: 1685892283432,
      blockers: 'Working on a backend Go project',
      completed: 'Working on a backend Go project',
      planned: 'Working on a backend Go project',
      type: 'user',
      userId: 'YleviOe1SsOML8eitV9W',
    },
    {
      id: 'KYvOM36StltlBNxtW9Mm',
      date: 1685577600000,
      createdAt: 1685616571070,
      blockers: 'Working on a backend Go project',
      completed: 'Working on a backend Go project',
      planned: 'Working on a backend Go project',
      type: 'user',
      userId: 'YleviOe1SsOML8eitV9W',
    },
    {
      id: 'T8GZ191H8lVTnGBB3tAQ',
      date: 1685318400000,
      createdAt: 1685374251104,
      blockers: 'Implement error handling for API endpoints',
      completed: 'Implement error handling for API endpoints',
      planned: 'Implement error handling for API endpoints',
      type: 'user',
      userId: 'YleviOe1SsOML8eitV9W',
    },
    {
      id: 'h3eK4lVB5PlOZXX9RFFP',
      date: 1685750400000,
      createdAt: 1685783692663,
      blockers: 'Working on a backend Go project',
      completed: 'Working on a backend Go project',
      planned: 'Working on a backend Go project',
      type: 'user',
      userId: 'YleviOe1SsOML8eitV9W',
    },
    {
      id: 'jng8Zlsjr90EuGbBQisG',
      date: 1685059200000,
      createdAt: 1685115243500,
      blockers: 'Working on a backend Go project',
      completed: 'Working on a backend Go project',
      planned: 'Working on a backend Go project',
      type: 'user',
      userId: 'YleviOe1SsOML8eitV9W',
    },
    {
      id: 'nFTXyHfbufj7XY2mguVX',
      date: 1685491200000,
      createdAt: 1685506497607,
      blockers: 'Implement error handling for API endpoints',
      completed: 'Implement error handling for API endpoints',
      planned: 'Implement error handling for API endpoints',
      type: 'user',
      userId: 'YleviOe1SsOML8eitV9W',
    },
    {
      id: 'sG4sUGTILmxaby9xmU3I',
      date: 1685404800000,
      createdAt: 1685453697666,
      blockers: 'Working on a backend Go project',
      completed: 'Working on a backend Go project',
      planned: 'Working on a backend Go project',
      type: 'user',
      userId: 'YleviOe1SsOML8eitV9W',
    },
    {
      id: 'xxvvSUglhJQNnHWVyEZ9',
      date: 1685232000000,
      createdAt: 1685257952297,
      blockers: 'Waiting for database access credentials',
      completed: 'Waiting for database access credentials',
      planned: 'Waiting for database access credentials',
      type: 'user',
      userId: 'YleviOe1SsOML8eitV9W',
    },
  ],
};

module.exports = { standupOne };
