const userDetailsApi = {
  message: 'Tasks returned successfully!',
  tasks: [
    {
      id: 'BMc4Bgy7FD7BOEa0NZzP',
      percentCompleted: 100,
      endsOn: 1690437548,
      github: {
        issue: { id: 1806764661, assignee: 'sahsisunny', status: 'open' },
      },
      createdBy: 'ankush',
      assignee: 'sunny-s',
      title: 'Sync Discord User to RDS backend ',
      type: 'feature',
      priority: 'TBD',
      startedOn: 1689553319.9,
      status: 'VERIFIED',
      assigneeId: 'jbGcfZLGYjHwxQ1Zh8ZJ',
    },
    {
      id: 'CyGNTPGoA7Cgi3bbb3Mt',
      percentCompleted: 100,
      endsOn: 1684900256,
      isNoteworthy: true,
      createdBy: 'ankush',
      lossRate: { dinero: 200, neelam: 0 },
      assignee: 'sunny-s',
      title: 'Collapse non-interesting tasks or PRs in member details page',
      type: 'feature',
      priority: 'MEDIUM',
      completionAward: { dinero: 3000, neelam: 0 },
      startedOn: 1680397446.1,
      status: 'VERIFIED',
      assigneeId: 'jbGcfZLGYjHwxQ1Zh8ZJ',
    },
    {
      id: 'F2A6XVGgM3IshzEd5niL',
      percentCompleted: 100,
      endsOn: 1688445662,
      isNoteworthy: false,
      createdBy: 'ankush',
      lossRate: { dinero: 100, neelam: 0 },
      assignee: 'sunny-s',
      title: 'Status site should use cloudinary images',
      type: 'feature',
      priority: 'HIGH',
      completionAward: { dinero: 1000, neelam: 0 },
      startedOn: 1680398131.277,
      status: 'VERIFIED',
      assigneeId: 'jbGcfZLGYjHwxQ1Zh8ZJ',
    },
    {
      id: 'Hiu2YqW37s0JhmYkIS6g',
      percentCompleted: 100,
      endsOn: 1690250670,
      github: { issue: { id: 1807299477, status: 'open' } },
      createdBy: 'ankush',
      assignee: 'sunny-s',
      title: 'Add query parameter for user search in standup page',
      type: 'feature',
      priority: 'TBD',
      status: 'VERIFIED',
      assigneeId: 'jbGcfZLGYjHwxQ1Zh8ZJ',
    },
    {
      id: 'UkFCn3Tz0vfkPCMPV40D',
      percentCompleted: 100,
      endsOn: 1691108792,
      github: { issue: { id: 1823003577, status: 'open' } },
      createdBy: 'ankush',
      assignee: 'sunny-s',
      title: 'Implement Intersection Observer to Fetch the tasks',
      type: 'feature',
      priority: 'TBD',
      status: 'VERIFIED',
      assigneeId: 'jbGcfZLGYjHwxQ1Zh8ZJ',
    },
    {
      id: 'WCG9GtacLJCOabaQLtOk',
      percentCompleted: 100,
      endsOn: 1692921600,
      github: { issue: { id: 1828790730, status: 'open' } },
      createdBy: 'ankush',
      assignee: 'sunny-s',
      title: 'Add Filter and Search Bar to Tasks Page',
      type: 'feature',
      priority: 'TBD',
      status: 'RELEASED',
      assigneeId: 'jbGcfZLGYjHwxQ1Zh8ZJ',
    },
    {
      id: 'hLRaaOcO5UW2GnQwB9ls',
      percentCompleted: 100,
      endsOn: 1690250695,
      github: {
        issue: { id: 1815135659, assignee: 'sahsisunny', status: 'open' },
      },
      createdBy: 'ankush',
      assignee: 'sunny-s',
      title: 'Mine Page Tasks Not Showing',
      type: 'feature',
      priority: 'TBD',
      startedOn: 1689989190.844,
      status: 'VERIFIED',
      assigneeId: 'jbGcfZLGYjHwxQ1Zh8ZJ',
    },
    {
      id: 'qaCqdCTjRyX1EPLuv1mJ',
      percentCompleted: 40,
      endsOn: 1693504200,
      github: {
        issue: { id: 1847136216, assignee: 'biswanathTewari', status: 'open' },
      },
      createdBy: 'ankush',
      assignee: 'sunny-s',
      title: 'Test Cases for QR scanning feature',
      type: 'feature',
      priority: 'TBD',
      status: 'IN_PROGRESS',
      assigneeId: 'jbGcfZLGYjHwxQ1Zh8ZJ',
    },
    {
      id: 'xylBsqi7LayeiZVlJfUr',
      percentCompleted: 50,
      endsOn: 1693161000,
      github: { issue: { id: 1851253319, status: 'open' } },
      createdBy: 'amitprakash',
      assignee: 'sunny-s',
      title: '`/task` command to  show assignee task details ',
      type: 'feature',
      priority: 'TBD',
      status: 'IN_PROGRESS',
      assigneeId: 'jbGcfZLGYjHwxQ1Zh8ZJ',
    },
  ],
};

module.exports = { userDetailsApi };
